{% set name = "aws-c-auth" %}
{% set version = "0.6.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 2b6b05e046227f87c39d0dd821759273c80e864689dfb36bbc64bed86dc8336f

build:
  number: 5
  run_exports:
    - {{ pin_subpackage("aws-c-auth", max_pin="x.x.x") }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - ninja
  host:
    - aws-c-cal
    - aws-c-common
    - aws-c-http
    - aws-c-io
    - aws-c-sdkutils

test:
  commands:
    - test -f $PREFIX/lib/libaws-c-auth${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/auth/auth.h  # [unix]
    - if not exist %LIBRARY_INC%\\aws\\auth\\auth.h exit 1          # [win]
    - if not exist %PREFIX%\\Library\\bin\\aws-c-auth.dll exit 1  # [win]

about:
  home: https://github.com/awslabs/aws-c-auth
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'C99 library implementation of AWS client-side authentication: standard credentials providers and signing.'
extra:
  recipe-maintainers:
    - xhochy
    - conda-forge/aws-sdk-cpp
